class AddYfcaseOtherFieldsToYfcase < ActiveRecord::Migration[6.0]
  def change
    add_column :yfcases, :other_address, :string
    add_column :yfcases, :auction_day_1, :date
    add_column :yfcases, :auction_day_2, :date
    add_column :yfcases, :auction_day_3, :date
    add_column :yfcases, :auction_day_4, :date
    add_column :yfcases, :floor_price_1, :integer
    add_column :yfcases, :floor_price_2, :integer
    add_column :yfcases, :floor_price_3, :integer
    add_column :yfcases, :floor_price_4, :integer
    add_column :yfcases, :click_1, :integer
    add_column :yfcases, :click_2, :integer
    add_column :yfcases, :click_3, :integer
    add_column :yfcases, :click_4, :integer
    add_column :yfcases, :monitor_1, :integer
    add_column :yfcases, :monitor_2, :integer
    add_column :yfcases, :monitor_3, :integer
    add_column :yfcases, :monitor_4, :integer
    add_column :yfcases, :margin_1, :integer
    add_column :yfcases, :margin_2, :integer
    add_column :yfcases, :margin_3, :integer
    add_column :yfcases, :margin_4, :integer
    add_column :yfcases, :auction_notes, :string
    add_column :yfcases, :first_survey_day, :date
    add_column :yfcases, :other_survey_day, :date
    add_column :yfcases, :foreclosure_announcement_title, :string
    add_column :yfcases, :foreclosure_announcement_link, :string
    add_column :yfcases, :object_photo_title, :string
    add_column :yfcases, :object_photo_link, :string
    add_column :yfcases, :net_price_registration_market_price_title, :string
    add_column :yfcases, :net_price_registration_market_price_link, :string
    add_column :yfcases, :net_price_registration_map_title, :string
    add_column :yfcases, :net_price_registration_map_link, :string
    add_column :yfcases, :net_price_registration_photo_title, :string
    add_column :yfcases, :net_price_registration_photo_link, :string
    add_column :yfcases, :auction_record_title, :string
    add_column :yfcases, :auction_record_link, :string
    add_column :yfcases, :other_notes, :string
    add_column :yfcases, :survey_resolution, :string
    add_column :yfcases, :final_decision, :string
    add_column :yfcases, :occupy, :string
    add_column :yfcases, :register, :string
    add_column :yfcases, :parking_space, :string
    add_column :yfcases, :management_fee, :string
    add_column :yfcases, :rent, :string
    add_column :yfcases, :leak, :string
    add_column :yfcases, :easy_parking, :string
    add_column :yfcases, :railway, :string
    add_column :yfcases, :vegetable_market, :string
    add_column :yfcases, :supermarket, :string
    add_column :yfcases, :school, :string
    add_column :yfcases, :park, :string
    add_column :yfcases, :post_office, :string
    add_column :yfcases, :main_road, :string
    add_column :yfcases, :water_and_power_failure, :string
    add_column :yfcases, :good_vision, :string
  end
end
